### ISSUE TITLE
proposal for an extension to add : logo packager

### ISSUE THREAD

**Issue by alezzacreative** [HarshilPatel007/Inkscape-Extra-Features#2]
hello 
am suggesting to make an extension similar to this illustrator plugin where when you finish a logo you package it in multiple formats and export them so it can ease the life of logo designers instead of redoing it after every changes manually.
 description start in 1:00 in this video  https://www.youtube.com/watch?v=3DtO6DYJz_0
full options description  :  https://www.youtube.com/watch?v=6XQXrx4WIr8&feature=youtu.be
its official page : https://thelogopackage.com/
thank you

**Comment by HarshilPatel007** [comment]
> hello
> am suggesting to make an extension similar to this illustrator plugin where when you finish a logo you package it in multiple formats and export them so it can ease the life of logo designers instead of redoing it after every changes manually.
> description start in 1:00 in this video https://www.youtube.com/watch?v=3DtO6DYJz_0
> full options description : https://www.youtube.com/watch?v=6XQXrx4WIr8&feature=youtu.be
> its official page : https://thelogopackage.com/
> thank you

Hi @alezzacreative, 
thanks for find interest in this plugin.
from what I've seen is, 'thelogopackage' plugin creates a new canvas/artboard for each logo and this is not possible into Inkscape because, Inkscape doeasn't supports multiple canvas/artboard.
But, If there any ways to strats with, I'm happy to do it.
